import json
from pathlib import Path

BASE_DIR = Path("ai-platform/generated_apps")


def run_builder(spec: dict, design: dict) -> dict:
    app_name = spec.get("app_name", "generated_saas_app")
    app_dir = BASE_DIR / app_name
    app_dir.mkdir(parents=True, exist_ok=True)

    (app_dir / "README.md").write_text(
        f"# {app_name}\n\nGenerated by AI platform pipeline.\n"
    )
    (app_dir / "spec.json").write_text(json.dumps(spec, indent=2))
    (app_dir / "design.json").write_text(json.dumps(design, indent=2))

    return {
        "app_name": app_name,
        "path": str(app_dir),
        "features": spec.get("features", []),
        "status": "completed",
    }
